Разметка всех страниц
htmlacademy-htmlcss/1859627-sedona-34 pull request #2
Opened 2022-05-26 15:48 UTC by Panyatna

---
:mortar_board: [Разметка всех страниц](https://up.htmlacademy.ru/htmlcss/34/user/1859627/tasks/4)

:boom: https://htmlacademy-htmlcss.github.io/1859627-sedona-34/2/

2022-05-28 07:10 UTC, Espanol-nikkol requested changes

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +            <a class="navigation-link" href="#">Гостиницы</a>
это наш каталог, можно на него ссылку сразу поставить

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +            <a class="navigation-link" href="#">Главная</a>
нужна ли нам ссылка на главную с главной? или это на самом деле не должно быть ссылкой?

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +            <a class="navigation-link" href="#">Хочу сюда!</a>
А если бы полностью реализовывали, то куда бы она вела? Или может это таки кнопка?

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +              <span class="visually-hidden">Поиск</span>
скорее все-таки кнопка
Как и избранное

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +              <img src="#" alt="Сувенир">
точно контентное изображение?

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +        <input type="email" name="email" id="#" placeholder="Ваш e-mail">
в форму надо обернуть

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +        <p class="tel">+7 (812) 812-12-12</p>
ссылочка должна быть

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +      <section class="footer-contacts">
не, это не отдельная секция
Нет законченного смысла, который был бы замкнут в этой секции

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +      <section class="footer-social">
в футере в принципе нет особого смысла выделять секции. Он сам по себе уже секция с определённым смыслом

2022-05-28 07:10 UTC, Espanol-nikkol commented on index.html
> +        <h2 class="visually-hidden">Контакты</h2>
ну а если выделяешь, то список соцсетей - это не очень контакты)
Вот соцсети и телефон - ну да, контакты

2022-05-30 17:00 UTC, Panyatna commented on index.html
> +            <a class="navigation-link" href="#">Гостиницы</a>
Добавил ссылку так если бы я сверстал страницу каталога.

2022-05-30 17:00 UTC, Panyatna commented on index.html
> +            <a class="navigation-link" href="#">Главная</a>
Тут два варианта: либо мы делаем ссылку, но пустую, чтобы не переходило с главной на главную, либо мы вообще не делаем это ссылкой, но тогда кнопка-ссылка на главную будет не полноценной. Оставить лучше пустой даже, чтобы курсор не менял своего вида?

2022-05-30 17:00 UTC, Panyatna commented on index.html
> +            <a class="navigation-link" href="#">Хочу сюда!</a>
Думаю это кнопка, которая открывает окно с формой как на макете "Поиск гостиницы в Седоне". Исправил на кнопку.

2022-05-30 17:00 UTC, Panyatna commented on index.html
> +              <span class="visually-hidden">Поиск</span>
Исправил.

2022-05-30 17:00 UTC, Panyatna commented on index.html
> +              <img src="#" alt="Сувенир">
Изменил на svg картинки.

2022-05-30 17:00 UTC, Panyatna commented on index.html
> +        <input type="email" name="email" id="#" placeholder="Ваш e-mail">
Обернул.

2022-05-30 17:01 UTC, Panyatna commented on index.html
> +        <p class="tel">+7 (812) 812-12-12</p>
Ссылочку сделал.

2022-05-30 17:01 UTC, Panyatna commented on index.html
> +      <section class="footer-contacts">
Удалил.

2022-05-30 17:01 UTC, Panyatna commented on index.html
> +      <section class="footer-social">
Удалил все секции. А как тогда разбить на блоки элементы? Или в этом нет необходимости?

2022-05-30 17:01 UTC, Panyatna commented on index.html
> +        <h2 class="visually-hidden">Контакты</h2>
Не понял, что ты написал, но исправил.

2022-06-02 13:54 UTC, Espanol-nikkol requested changes

2022-06-02 13:54 UTC, Espanol-nikkol commented on index.html
> +            <a class="navigation-link" href="#">Главная</a>
Да, вполне можно

2022-06-02 13:54 UTC, Espanol-nikkol commented on index.html
> +              <img src="#" alt="Сувенир">
Уже лучше. А мы предполагаем с ними взаимодействие?

2022-06-02 14:23 UTC, Espanol-nikkol approved these changes

2022-06-02 14:24 UTC, merged