Добавляет графику
htmlacademy-htmlcss/1859627-sedona-34 pull request #3
Opened 2022-06-02 16:07 UTC by Panyatna

2022-06-03 01:11 UTC, Espanol-nikkol requested changes

2022-06-03 01:11 UTC, Espanol-nikkol commented on index.html
>              <p class="advantages-image">
класс `advantages-image` можно повесить на саму картинку
Ну и зачем нам тут p? У нас ведь нет никакого абзаца, только картинка и всё

2022-06-03 01:11 UTC, Espanol-nikkol commented on index.html
> +        <img class="logo" src="images/index-background.jpg" alt="Логотип Седоны">
стоит размеры проставить для img
alt не подходит. Это не логотип, точно. Что-нибудь типа "Живописные горы в Седоне"

2022-06-03 01:11 UTC, Espanol-nikkol commented on index.html
> +          <img src="images/footer-logo.svg" alt="Логотип">
Размеры
Альт поточнее сделать бы, у нас же есть логотип Седоны, а тут логотип уже другой

2022-06-03 14:15 UTC, Panyatna commented on index.html
>              <p class="advantages-image">
И правда. Исправил.

2022-06-03 14:19 UTC, Panyatna commented on index.html
> +        <img class="logo" src="images/index-background.jpg" alt="Логотип Седоны">
Исправил)

2022-06-03 14:37 UTC, Panyatna commented on index.html
> +          <img src="images/footer-logo.svg" alt="Логотип">
Сделал.

2022-06-06 14:05 UTC, Espanol-nikkol approved these changes

2022-06-06 14:12 UTC, merged